apiVersion: batch/v1
kind: Job
metadata:
  name: ingext-community-init
  namespace: {{ .Release.Namespace }}
spec:
  parallelism: 1    
  completions: 1
  ttlSecondsAfterFinished: 3600    
  template:         
    metadata:
      name: ingext-community-init
    spec:
      containers:
      - name: account-init
        image: public.ecr.aws/ingext/account_init:latest
        env:
          - name: ACCOUNT
            value: {{ .Values.account }}

        command:
        - /bin/sh
        - -c
        - |
          cd /scripts
          cp /scripts/etcd_config.json /etc/etcd_config.json
          /scripts/rbac_upgrade.sh {{ .Values.account }}
          mkdir /etc/schemas
          cp /scripts/schemas/*.json /etc/schemas/
          /scripts/ingext_cli esv7 create ingext_audit /etc/schemas/schema_audit_v7.json
          /scripts/ingext_cli esv7 create platform_processor /etc/schemas/platform_processor_v7.json
          /scripts/ingext_cli esv7 create globalasset /etc/schemas/schema_globalasset.json
          /scripts/ingext_cli esv7 create metric_incident /etc/schemas/metric_incident_mapping_v7.json
          /scripts/ingext_cli esv7 create metric_alert /etc/schemas/metric_alert_mapping_v7.json
          /scripts/ingext_cli esv7 create metric_data /etc/schemas/metric_data_mapping_v7.json
          /scripts/ingext_cli esv7 create eventwatch /etc/schemas/eventwatch_v7.json
          /scripts/ingext_cli esv7 create behavior /etc/schemas/behavior_mapping_v7.json
          /scripts/ingext_cli esv7 create behavior_summary  /etc/schemas/behavior_summary_mapping_v7.json
      restartPolicy: Never