apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-fluency7
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 8004
      targetPort: 8004
      name: ui
  selector:
    "ingext.io/app": "{{ .Release.Namespace }}-fluency7"
