apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 8002
      targetPort: 8002
      name: api
  selector:
    "ingext.io/app": "{{ .Release.Namespace }}-api"
